[package]
name = "pulsar-network"
version = "0.1.2"
edition = "2018"
license = "MIT"
description = "A connection Library for the Pulsar Network, a distributed hash table peer-to-peer messaging protocol."
repository = "https://github.com/seg-software/rust-pulsar-network"
readme = "README.md"

[dependencies]
neutrondb = "0.9.19"
stellar-notation = "0.9.18"
opis = "1.0.0"
