[package]
name = "pulsar-network"
version = "1.0.0"
edition = "2018"
license = "MIT"
description = "Pulsar Network is a distributed hash table peer-to-peer messaging protocol for the Astreuos Blockchain written in Rust."
repository = "https://github.com/stelar-software/rust-pulsar-network"
readme = "README.md"

[dependencies]
neutrondb = "2.2.0"
fides = "0.4.0"